# Generated by Django 2.1.2 on 2018-10-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0002_auto_20181007_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
    ]
