# Generated by Django 2.1.2 on 2018-10-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0004_userresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='User',
        ),
    ]
