# Generated by Django 2.1.2 on 2018-10-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0007_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='UserData',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
