# Generated by Django 2.1.2 on 2018-10-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0008_auto_20181007_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='UserResponse',
        ),
    ]
