# Generated by Django 2.1.2 on 2018-10-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0009_auto_20181007_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='Useru',
        ),
    ]
