# Generated by Django 2.1.2 on 2018-10-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0010_auto_20181007_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Useru',
            new_name='User',
        ),
    ]
