# Generated by Django 2.1.2 on 2018-10-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0011_auto_20181007_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=30)),
                ('person_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
