# Generated by Django 2.1.2 on 2018-10-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0013_auto_20181007_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserD',
        ),
    ]
