# Generated by Django 2.1.2 on 2018-10-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0014_auto_20181007_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserD',
            new_name='Usera',
        ),
    ]
