# Generated by Django 2.1.2 on 2018-10-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0016_auto_20181007_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userb',
            new_name='Userz',
        ),
    ]
