# Generated by Django 2.1.2 on 2018-10-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0017_auto_20181007_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userz',
            new_name='Userf',
        ),
    ]
