# Generated by Django 2.1.2 on 2018-10-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0018_auto_20181007_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userf',
            new_name='User_f',
        ),
    ]
