# Generated by Django 2.1.2 on 2018-10-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0019_auto_20181013_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_f',
            options={'managed': False},
        ),
    ]
