# Generated by Django 2.1.2 on 2018-10-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0020_auto_20181013_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
