# Generated by Django 2.1.2 on 2018-10-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0022_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
