# Generated by Django 2.1.2 on 2018-10-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0024_person_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='UserData',
        ),
    ]
