# Generated by Django 2.1.2 on 2018-10-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0025_auto_20181013_0750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='Userinfo',
        ),
    ]
