# Generated by Django 2.1.2 on 2018-10-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0026_auto_20181013_0801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userinfo',
            new_name='Useri',
        ),
    ]
