# Generated by Django 2.1.2 on 2018-10-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0027_auto_20181013_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Useri',
        ),
    ]
