# Generated by Django 2.1.2 on 2018-11-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0028_auto_20181013_0812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Useru',
            new_name='UserData',
        ),
    ]
