# Generated by Django 2.1.2 on 2018-11-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0029_auto_20181104_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
