# Generated by Django 2.1.2 on 2018-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_response', '0030_auto_20181104_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(default=None, max_length=30)),
                ('person_mobile', models.CharField(default=None, max_length=30, unique=True)),
                ('date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
